#!/bin/sh

# Translate a text file from one language to another language.
#
# Syntax:
#
#    translate-file-using-ollama-muse-glimmer <src-file> <src-language> <dst-file> <dst-language>
#
# Model examples:
#
#    - muse-glimmer:30b-mlx
#
set -euf

## https://github.com/sixarm/unix-shell-script-kit

EXIT_CANTCREATE=73

out() {
        >&1 printf %s\\n "${*}"
}

err() {
        >&2 printf %s\\n "${*}"
}

die() {
       n="$1" ; shift ; err "${*}"; exit "$n"
}

## Main script starts here

arg_model="$1"
arg_src_file="$2"
arg_src_language="$3"
arg_dst_file="$4"
arg_dst_language="$5"

test -e "$arg_src_file" || die $EXIT_CANTCREATE "Source file does not exist: $arg_src_file"
test ! -e "$arg_dst_file" || die $EXIT_CANTCREATE "Destination file already exists: $arg_dst_file"

cat "$arg_src_file" | 
ollama run "$arg_model" --hidethinking --nowordwrap \
"Translate from $arg_src_language to $arg_dst_language." > \
"$arg_dst_file.wip"
mv "$arg_dst_file.wip" "$arg_dst_file"
