#!/bin/sh

# Translate a text file from one language to another language.
#
# Syntax:
#
#    translate-file-using-ollama <model> <src-file> <src-language> <dst-file> <dst-language>
#
# Model examples:
#
#    - muse-glimmer:30b-mlx
#    - qwen3.8:27b-mlx
#
set -euf

## https://github.com/sixarm/unix-shell-script-kit

EXIT_CANTCREATE=73

out() {
        >&1 printf %s\\n "${*}"
}

err() {
        >&2 printf %s\\n "${*}"
}

die() {
       n="$1" ; shift ; err "${*}"; exit "$n"
}

## Main script starts here

arg_model="$1"
arg_src_file="$2"
arg_src_language="$3"
arg_dst_file="$4"
arg_dst_language="$5"

test -e "$arg_src_file" || die $EXIT_CANTCREATE "Source file does not exist: $arg_src_file"
test ! -e "$arg_dst_file" || die $EXIT_CANTCREATE "Destination file already exists: $arg_dst_file"

prompt=$(cat << EOM
Role: You are a professional, elite literary translator specializing in adapting 
$arg_src_language literature into culturally natural, highly descriptive $arg_dst_language.

Task: Translate the provided text from $arg_src_language into $arg_dst_language.

Rules:
1. Maintain consistent terminology and character name translations across all segments.
2. Avoid literal translationese (don\'t translate $arg_src_language syntax structures directly). 
3. Use idiomatic, flowing $arg_dst_language that reads like native prose.
4. Keep the emotional tone, pacing, and descriptive depth of the original text.
5. Output ONLY the completed translation.
6.Do not include any preambles, explanations, or conversational filler.
EOM
)

cat "$arg_src_file" | 
ollama run "$arg_model" --hidethinking --nowordwrap "$prompt" > \
"$arg_dst_file.wip"
mv "$arg_dst_file.wip" "$arg_dst_file"
