#!/bin/sh

# Translate text from one language to another language.
#
# Syntax:
#
#    translate-text-using-ollama-muse-glimmer <src-text> <src-language> <dst-language>
#
# Implementation:
#
#    - Use Ollama Muse Glimmer 
#

set -euf
src_text="$1"
src_language="$2"
dst_language="$3"
printf "%s" "$src_text" | 
ollama run muse-glimmer:30b-mlx --hidethinking --nowordwrap \
"Translate from $src_language into $dst_language."
